apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: trade-feed
  name: trade-feed
spec:
  ports:
    - name: "tcp"
      port: 18086
      targetPort: 18086
  selector:
    io.kompose.service: trade-feed
