apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "default/splunk-otel-collector"
      labels:
        io.kompose.service: account-service
    spec:
      containers:
        - args:
            - ./gradlew
            - bootRun
          env:
            - name: DATABASE_TCP_HOST
              value: database
            - name: PEOPLE_SERVICE_HOST
              value: people-service
          image: quay.io/phagen/traderx/account-service:0.1
          name: account-service
          ports:
            - containerPort: 18088
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: account-service-cm
          workingDir: /account-service
          resources:
            requests:
              memory: "600Mi"
              cpu: "256m"
            limits:
              memory: "768Mi"
              cpu: "512m"
      restartPolicy: Always
      volumes:
        - configMap:
            name: account-service-cm
          name: account-service-cm
