apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
    - name: "18082"
      port: 18082
      targetPort: 18082
    - name: "18083"
      port: 18083
      targetPort: 18083
    - name: "18084"
      port: 18084
      targetPort: 18084
  selector:
    io.kompose.service: database
