apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: trade-processor
  name: trade-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trade-processor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "default/splunk-otel-collector"
      labels:
        io.kompose.service: trade-processor
    spec:
      containers:
        - args:
            - ./gradlew
            - bootRun
          env:
            - name: DATABASE_TCP_HOST
              value: database
            - name: TRADE_FEED_HOST
              value: trade-feed   
          image: quay.io/phagen/traderx/trade-processor:0.1.1 
          imagePullPolicy: Always
          name: trade-processor
          ports:
            - containerPort: 18091
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: trade-processor-cm
          workingDir: /trade-processor
      restartPolicy: Always
      volumes:
        - configMap:
            name: trade-processor-cm
          name: trade-processor-cm
