apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: reference-data
  name: reference-data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reference-data
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"      
      labels:
        io.kompose.service: reference-data
    spec:
      containers:
        - args:
            - npm
            - run
            - start
          image: quay.io/phagen/traderx/reference-data:0.1
          imagePullPolicy: Always
          name: reference-data
          ports:
            - containerPort: 18085
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: reference-data-cm
          workingDir: /reference-data
      restartPolicy: Always
      volumes:
        - configMap:
            name: reference-data-cm
          name: reference-data-cm
