apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: reference-data
  name: reference-data
spec:
  ports:
    - name: "tcp"
      port: 18085
      targetPort: 18085
  selector:
    io.kompose.service: reference-data
