apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: people-service
  name: people-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: people-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        #instrumentation.opentelemetry.io/inject-dotnet: "true"
        #instrumentation.opentelemetry.io/otel-dotnet-auto-runtime: "linux-x64"
      labels:
        io.kompose.service: people-service
    spec:
      containers:
        #for now enable the right platform  as required 
        - image: quay.io/phagen/traderx/people-service:0.1.5amd 
        #- image: quay.io/phagen/traderx/people-service:0.1.5arm
          imagePullPolicy: Always
          name: people-service
          env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED
            value: "false"
          - name: OTEL_DOTNET_AUTO_LOGS_ENABLED
            value: "true"
          - name: OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED
            value: "false"  
          - name: OTEL_LOG_LEVEL
            value: "debug"
          - name:  CORECLR_ENABLE_PROFILING
            value: "1" 
          - name: OTEL_SERVICE_NAME
            value: people-service
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4318"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.version=0.1.5"
          - name: SPLUNK_ENV_NAME  
            value: "xtrader-workshop"  
          ports:
            - containerPort: 18089
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: people-service-cm
          workingDir: /people-service
      restartPolicy: Always
      volumes:
        - configMap:
            name: people-service-cm
          name: people-service-cm

