apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: people-service
  name: people-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: people-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        #instrumentation.opentelemetry.io/inject-dotnet: "true"
        #instrumentation.opentelemetry.io/otel-dotnet-auto-runtime: "linux-x64"
      labels:
        io.kompose.service: people-service
    spec:
      containers:
        - image: quay.io/phagen/traderx/people-service:0.1.4
          imagePullPolicy: Always
          name: people-service
          env:
          - name: OTEL_LOG_LEVEL
            value: "debug"
          - name: OTEL_SERVICE_NAME
            value: people-service
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "splunk-otel-collector-agent:4317"            
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "deployment.environment=xtrader-workshop,service.version=0.1.4"
          ports:
            - containerPort: 18089
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: people-service-cm
          workingDir: /people-service
      restartPolicy: Always
      volumes:
        - configMap:
            name: people-service-cm
          name: people-service-cm
