apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: position-service
  name: position-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: position-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "default/splunk-otel-collector"      
      labels:
        io.kompose.service: position-service
    spec:
      containers:
        - args:
            - ./gradlew
            - bootRun
          env:
            - name: DATABASE_TCP_HOST
              value: database
          image: quay.io/phagen/traderx/position-service:0.1 
          imagePullPolicy: Always
          name: position-service
          ports:
            - containerPort: 18090
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: position-service-cm
          workingDir: /position-service
          resources:
            requests:
              memory: "768Mi"
              cpu: "256m"
            limits:
              memory: "1024Mi"
              cpu: "512m"
      restartPolicy: Always 
      volumes:
        - configMap:
            name: position-service-cm
          name: position-service-cm
