apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: position-service
  name: position-service
spec:
  ports:
    - name: "tcp"
      port: 18090
      targetPort: 18090
  selector:
    io.kompose.service: position-service
