apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: people-service
  name: people-service
spec:
  ports:
    - name: "tcp"
      port: 18089
      targetPort: 18089
  selector:
    io.kompose.service: people-service
