apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: trade-processor
  name: trade-processor
spec:
  ports:
    - name: "tcp"
      port: 18091
      targetPort: 18091
  selector:
    io.kompose.service: trade-processor
