apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: trade-service
  name: trade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trade-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "default/splunk-otel-collector"
      labels:
        io.kompose.service: trade-service
    spec:
      containers:
        - args:
            - ./gradlew
            - bootRun
          env:
            - name: ACCOUNT_SERVICE_HOST
              value: account-service
            - name: DATABASE_TCP_HOST
              value: database
            - name: PEOPLE_SERVICE_HOST
              value: people-service
            - name: REFERENCE_DATA_HOST
              value: reference-data
            - name: TRADE_FEED_HOST
              value: trade-feed
          image: quay.io/phagen/traderx/trade-service:0.1
          imagePullPolicy: Always
          name: trade-service
          ports:
            - containerPort: 18092
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: trade-service-cm
          workingDir: /trade-service
          resources:
            requests:
              memory: "600Mi"
              cpu: "256m"
            limits:
              memory: "768Mi"
              cpu: "512m"
      restartPolicy: Always
      volumes:
        - configMap:
            name: trade-service-cm
          name: trade-service-cm
