apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: ingress
  name: ingress
spec:
  type: LoadBalancer 
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: ingress
