apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: loadgen
  name: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loadgen
  template:
    metadata:
      labels:
        io.kompose.service: loadgen
    spec:
      containers:
        - name: loadgen  # Container name added here
          image: quay.io/phagen/traderx/loadgen-service:0.1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "75Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "200m"
      restartPolicy: Always
