apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: database
    spec:
      containers:
        - args:
            - ./run.sh
          env:
            - name: DATABASE_WEB_HOSTNAMES
              value: localhost
          image: quay.io/phagen/traderx/database:0.1
          name: database
          ports:
            - containerPort: 18082
              protocol: TCP
            - containerPort: 18083
              protocol: TCP
            - containerPort: 18084
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: database-cm
          workingDir: /database
      restartPolicy: Always
      volumes:
        - configMap:
            name: database-cm
          name: database-cm
