apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: web-front-end-angular
  name: web-front-end-angular
spec:
  ports:
    - name: "tcp"
      port: 18093
      targetPort: 18093
  selector:
    io.kompose.service: web-front-end-angular
